version: '3.1'

services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpassword
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ../sql:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  tomcat:
    image: tomcat
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - ../target:/usr/local/tomcat/webapps
